### PR TITLE
Add ERC1155 module, dual and interface with Component implementation

### LINKED ISSUE #572: migrate erc1155 contracts

### PR DESCRIPTION
**Pull request by cloudvenger**
Fixes #572 

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Added entry to CHANGELOG.md 
- [x] Tried the feature on a public network

### CODE REVIEW

**Comment by martriay** [comment]
Hello @cloudvenger, thanks for all the work put into this. As this is scheduled as part of our upcoming milestone and since we're way past the original agreed deadline (~3rd week of November 2023, or December ~15th as the latest extension) we'll be picking this up internally to complation. Thanks again for your contributions.

**Comment by cloudvenger** [comment]
Juste reading your message @martriay   
I send you a Telegram message to explain myself on the subject and trying to find a solution to contribute

**Comment by cloudvenger** [comment]
To help to continue/finish the impl of ERC-1155 in component version, here is the list of what was done :
- Creation of erc1155 modul in src/token
- Implementation of erc1155 Interface, Component, Receiver, Dual, Dual_receiver
- Implementation of Preset for ERC-1155
- Implementation of few unit tests for erc1155 component, receiver, dual & dual_receiver

Remains to be done :
- Implementing much more unit tests to have a much better test coverage
- Writing/Updating documentation for erc1155 component version

You can find a Smart Contract which used this erc1155 component version her :
https://testnet.starkscan.co/contract/0x01115205424b7d08d8895dd0d5c60d6f7beb5def65c749898d0864823f3dbb43#overview

The Smart Contract is recognized as ERC-1155 on voyager blockchain explorer
**_Important point_** : To be recognized as ERC-1155 Starkscan blockchain explorer, I needed to add the support interface of old ERC-1155 Interface `0xd9b67a26`. 
I did not add it in OpenZepplin erc-1155 impl but I add it in the constructor of the Smart Contract which used erc-1155 openzepplin component.

If you are any question, do not hesitate @martriay

**Comment by martriay** [comment]
Superseded by #896

**Pull request closed without merging**
