### PR TITLE
Release v0.16.0

### PR DESCRIPTION
**Pull request by immrsd**

### CODE REVIEW

**Review by ericnordelo — APPROVED** [review]
LGTM!

**Review by ggonzalez94 — APPROVED** [review]
LGTM

**Review by andrew-fleming — COMMENTED** [review]
We have to update a couple links in token_common that are v0.15.0: [line 15](https://github.com/OpenZeppelin/cairo-contracts/blob/main/docs/modules/ROOT/pages/api/token_common.adoc?plain=1#L15) and [line 49](https://github.com/OpenZeppelin/cairo-contracts/blob/main/docs/modules/ROOT/pages/api/token_common.adoc?plain=1#L49)

**Comment by immrsd** [comment]
> We have to update a couple links in token_common that are v0.15.0: [line 15](https://github.com/OpenZeppelin/cairo-contracts/blob/main/docs/modules/ROOT/pages/api/token_common.adoc?plain=1#L15) and [line 49](https://github.com/OpenZeppelin/cairo-contracts/blob/main/docs/modules/ROOT/pages/api/token_common.adoc?plain=1#L49)

Good catch! Fixed

**Review by andrew-fleming — COMMENTED** [review]
Ah one more thing, sorry! We need to add the spdx to [erc2981/interface.cairo](https://github.com/OpenZeppelin/cairo-contracts/blob/main/packages/token/src/common/erc2981/interface.cairo)

**Review by andrew-fleming — APPROVED** [review]
I think we're good to go! Release the Kraken!

**Pull request merged**
