### PR TITLE
Add financial system

### LINKED ISSUE #973: Add financial systems
**🧐 Motivation**
add cairo's financial systems

**📝 Details**
Ref: https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/finance

rewrite VestingWallet && VestingWalletCliff

### PR DESCRIPTION
**Pull request by zpano**
Fixes #973 

#### PR Checklist

- [x] Tests
- [ ] Documentation
- [ ] Added entry to CHANGELOG.md
- [ ] Tried the feature on a public network

### CODE REVIEW

**Comment by ericnordelo** [comment]
Hey @zpano, thanks for taking the time to contribute. Note that we expect the PR to contain a strong test suite before reviewing it, and documentation before merging it.

**Comment by zpano** [comment]
@ericnordelo How can i write an documentation?

**Comment by andrew-fleming** [comment]
Hey, @zpano! Thanks for opening the PR. Here are the basic guidelines for contributing: https://github.com/OpenZeppelin/cairo-contracts/blob/main/CONTRIBUTING.md

> How can i write an documentation?

An example of in-code docs: https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/token/erc20/erc20.cairo#L117-L124

And here's instructions for the docsite: https://github.com/OpenZeppelin/cairo-contracts/blob/main/CONTRIBUTING.md#documentation

Let us know if you have any questions

**Comment by immrsd** [comment]
Thank you for your contribution! 
From this point we're going to take over the implementation of Vesting Components, make the necessary changes and bring it to life

**Comment by ericnordelo** [comment]
Close as we already merged VestingComponent in #1116

**Pull request closed without merging**
