### PR TITLE
Bump scarb to v2.9.1

### PR DESCRIPTION
**Pull request by andrew-fleming**
Scarb's `fmt` command is bringing back trailing commas

This also bumps SN forge to v0.34.0

### CODE REVIEW

**Review by ericnordelo — COMMENTED** [review]
Looking good @andrew-fleming , I left a couple of comments. There seems to be some regression for the coverage tool after the update of foundry and scarb. Since you took the initiative, can you check that with them if necessary @andrew-fleming? cc @ggonzalez94 to be aware of coverage percentage issues.

**Review by ericnordelo — APPROVED** [review]
LGTM!

**Comment by andrew-fleming** [comment]
I commented out the cairo-coverage and codecov commands in the CI. I figured this is the easiest workaround until coverage is more stable

**Review by ericnordelo — APPROVED** [review]
Let's comment the coverage tool for the sake of fixing the transient dependencies issue.

**Pull request merged**
