### PR TITLE
style: update SPDX license identifiers

### PR DESCRIPTION
**Pull request by ca11ab1e**
#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Changelog entry

### CODE REVIEW

**Comment by martriay** [comment]
Great example of why we need to automate this. Not entirely sure what to do here since we won't be releasing this until 0.2.2 (0.2.1 is already malformed).

**Comment by ca11ab1e** [comment]
What's true is that current state of contracts is 0.2.1, not 0.2.0.
What's even more true, automatic handling of such stuff would be great.

**Review by martriay — CHANGES_REQUESTED** [review]
I think we're missing `accesscontrol.cairo` and we're good to go.

**Review by martriay — APPROVED** [review]
Please do not force push! It makes reviewing harder.

**Pull request merged**
