### PR TITLE
Implementing the ERC-1155, IERC-1155 and associatied test-script

### PR DESCRIPTION
**Pull request by LouGel**

### CODE REVIEW

**Comment by ponderingdemocritus** [comment]
What is the status of this branch?

**Comment by martriay** [comment]
It's been de-prioritized in favor of other more urgent features such as Account, ERC20, and ERC721 contracts. Now that we're settling onto a [reasonable extensibility pattern](https://community.starknet.io/t/contract-extensibility-pattern/210), we can start thinking about these other efforts as well (sorry, limited resources required us to focus on less stuff!).

This PR serves as a great base work, but it needs to be adapted to the latest version of the lib, as well as adopting the extensibility pattern.

**Comment by ponderingdemocritus** [comment]
No problem! We might pick it up if no one is working on it

**Comment by martriay** [comment]
Yeah that'd be great!

**Comment by martriay** [comment]
Superseded by #118

**Pull request closed without merging**
