### PR TITLE
Ownable: split assertion checks in two statements

### LINKED ISSUE #421: Ownable: split assertion checks in two statements
A misleading error message can happen when calling the guard `assert_only_owner`. 

**📝 Details**

The function `assert_only_owner` currently contains two assertion statements in the same with_attr block. The associated error message only concerns the second statement. Then, when this function is called with a `caller` being 0, the error message is `"Ownable: caller is not the owner"`, which is misleading.

**🔢 Code to reproduce bug**

Two files to reproduce it:
- `main.cairo`
  ```cairo
  %lang starknet
  
  from starkware.cairo.common.cairo_builtins import HashBuiltin
  from openzeppelin.access.ownable.library import Ownable
  
  func sum{syscall_ptr : felt*, pedersen_ptr : HashBuiltin*, range_check_ptr}(a : felt, b : felt) -> (sum : felt):
      Ownable.assert_only_owner()
      let (sum) = a + b
      return (sum)
  end
  ```

- `test_main.cairo`
  ```cairo
  from starkware.cairo.common.cairo_builtins import HashBuiltin

  from main import sum
    
  func test_sum{
      syscall_ptr : felt*, pedersen_ptr : HashBuiltin*, range_check_ptr
  }():
      sum(1, 2) # this raises "Ownable: caller is not the owner" instead of a message about zero address
      return ()
  end
  
  ```

### PR DESCRIPTION
**Pull request by achab**
Fixes #421  

This PR splits two checks about address in Ownable contracts in two separate `with_attr` statements. Currently, the error message only corresponds to the second check.

#### PR Checklist

- [x] Tests
- [ ] Documentation
- [ ] Changelog entry

### CODE REVIEW

**Review by andrew-fleming — APPROVED** [review]
Nice improvement, thank you!

**Comment by martriay** [comment]
Thanks for this improvement, it is now clear that we're not properly testing for the non owner case, just the zero address special case. We do have a test on ERC721SafeMintableMock, but not on actual library.

Could you add the missing tests?

**Comment by achab** [comment]
Hi there, thanks for the review! I've just added a small test to check that it reverts if the function `protected_function` is called by an account different from the owner.

**Review by martriay — APPROVED** [review]
Looks good! Thanks :)

**Pull request merged**
