### PR TITLE
Fix linter lack of package.json

### PR DESCRIPTION
**Pull request by martriay**
Fixes https://github.com/OpenZeppelin/cairo-contracts/issues/447.

### CODE REVIEW

**Review by ericnordelo — COMMENTED** [review]
Is the `npm install npm` line necessary?

**Comment by andrew-fleming** [comment]
> Is the `npm install npm` line necessary?

No, it's not needed. Good call

**Comment by martriay** [comment]
removed

**Review by ericnordelo — APPROVED** [review]
LGTM

**Pull request merged**
