### PR TITLE
Implement Scarb Workspaces and Modularize Codebase

### LINKED ISSUE #734: Suggestion: use Scarb workspaces
Use Scarb [workspaces](https://docs.swmansion.com/scarb/docs/reference/workspaces.html) to split the lib into packages.

**🧐 Motivation**
The library is already pretty broad (in terms of functionality) and sure to grow. There are times were a project does not need all of the features it offers. For example, say I want to use only access control and reentrancy guard. With the current structure, I'd have to pull in the whole `cairo-contracts` package (thought the unused parts would not be compiled).

With the use of workspaces, I could declare only the dependencies I need inside Scarb.toml, e.g.

```
[dependencies]
access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
security = { git = "https://github.com/OpenZeppelin/cairo-contracts.git" }
```

Note this is just a suggestion. I can see arguments for doing it both ways, just wanted to open a discussion.

### PR DESCRIPTION
**Pull request by ametel01**
Fixes #734   

### Changes Introduced

This PR implements Scarb workspaces and breaks down the OpenZeppelin Cairo contracts codebase into packages to improve modularity. This allows developers to import only the required libraries in a more granular manner, enhancing both usability and maintainability.

### Current Status

The PR is currently in draft status. Before proceeding further, I need the maintainers' opinions on how to best integrate the existing tests into their respective new packages. Any guidance on this integration will be greatly appreciated.

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Added entry to CHANGELOG.md 
- [ ] Tried the feature on a public network

### CODE REVIEW

**Comment by andrew-fleming** [comment]
Thanks for opening this PR, @ametel01!

> Before proceeding further, I need the maintainers' opinions on how to best integrate the existing tests into their respective new packages. Any guidance on this integration will be greatly appreciated.

Give us a little time to review and think about this and we'll provide feedback

**Comment by ericnordelo** [comment]
Hey @ametel01, thanks for taking the time. This is a solid base for the migration. Since we are still missing test organization, the test utils package, documentation updates around it, and workflows fix (class hashes update check, etc...), this PR can become quite big and complex to review. Then, I think it would be easier if we take it from here, keeping your contributions (commits). We had this as part of our next milestone, so we should be working on it very soon (it will be part of the next release).

**Comment by ericnordelo** [comment]
Thanks again @ametel01! Superseded by #1065.

**Comment by ametel01** [comment]
Hey @ericnordelo happy to have jumpstarted the transition

**Pull request closed without merging**
