### PR TITLE
Change the spelling of "StarkNet" to "Starknet"

### PR DESCRIPTION
**Pull request by kongtaoxing**
# Fixes Spell Issue 
Changes the spelling of "StarkNet" from "StarkNet" to "Starknet" everywhere in the doc following the recommendations in [this SNIP](https://community.starknet.io/t/snip-naming-convention-starknet-not-starknet).

#### PR Checklist

- [x] Documentation

### CODE REVIEW

**Comment by martriay** [comment]
is that SNIP conclusive? is this official already?

**Comment by kongtaoxing** [comment]
Yes, I think so, sir. After this _SNIP_ , Starknet team changed thir [twitter name](https://twitter.com/Starknet) from StarkNet to Starknet
image
And in recent [articles](https://medium.com/starkware/open-sourcing-the-starknet-prover-283d3e807c8b), the spelling of it was changed to *Starknet*, too
image

**Comment by kongtaoxing** [comment]
And now, the official website has been updated
https://www.starknet.io/en
https://starkware.co/starknet/

**Comment by martriay** [comment]
thanks. we're doing a [complete rewrite of the library at this moment](https://github.com/OpenZeppelin/cairo-contracts/tree/cairo-1), so these changes would conflict with it.

we'll make sure to take this new updated branding into account in our upcoming work!

**Review by martriay — APPROVED** [review]

**Pull request merged**
