### PR TITLE
feat: Add Merkle Proof Verifier

### LINKED ISSUE #936: Merkle proof verifier
See [MerkleProof.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7417c5946f8a213a8e61eca8d3c5247bf3854249/contracts/utils/cryptography/MerkleProof.sol)

### PR DESCRIPTION
**Pull request by boray**
Fixes #936 

I implemented [MerkleProof.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/7417c5946f8a213a8e61eca8d3c5247bf3854249/contracts/utils/cryptography/MerkleProof.sol) in Cairo.

This is a draft and needs improvement. It uses only Poseidon for now. That should be abstracted to work with Pedersen and Keccak. Testing coverage is narrow and should be extended. 

I am waiting for your comments.

#### PR Checklist

- [ ] Tests
- [ ] Documentation
- [ ] Added entry to CHANGELOG.md 
- [ ] Tried the feature on a public network

### CODE REVIEW

**Comment by ericnordelo** [comment]
Hey @boray thanks for taking the time! This would be a nice addition and we are happy to merge it after is finished and reviewed. We will be happy to review the PR after tests and logic are finished.

**Comment by ametel01** [comment]
Could we have this merged ASAP? I need it in a repo i'm working on and i'd rather skip implementing this from scratch

**Comment by ericnordelo** [comment]
Hey @ametel01, this PR is from an external contributor, and we will be happy to review it and merge it as soon as it is ready, It is also part of our roadmap for the next milestone, so we plan on working on that in the next three weeks. Note that Cairo 2.7 introduces some important changes, so we can't really release until we have the full cairo version out.

**Comment by ametel01** [comment]
@ericnordelo understandable

**Comment by augustbleeds** [comment]
@ericnordelo also waiting to use a MerkleProof Verifier library for some work we're doing at Chainlink. I see that the the rc's for Cairo 2.7 are out already. Do you have an idea of when this work could be completed?

**Comment by ericnordelo** [comment]
We will start working on it right after finishing this release. The reason is mainly [these changes](https://github.com/OpenZeppelin/cairo-contracts/pull/1065) that conflict and must be included first.

**Comment by ericnordelo** [comment]
Thanks again @boray for kickstarting the implementation. Since we have the issue as part of the current milestone, and it's been some time since this PR last update, we will take it further. Closing in favor of #1101

**Pull request closed without merging**
